#! /bin/bash

EXPIRING_DIR=/var/www/files/expiring/
cd "$EXPIRING_DIR"

TODAY=$(date "+%Y%m%d")

for DIR in `ls -d *`; do
    DIRDATE=`echo $DIR | tr -d -`
    if [[ "$DIRDATE" -lt "$TODAY" ]]
    then

        # Safe option. Moves expired files to a hidden directory for manual
        # deletion
        # mv "$DIR" .expired/"$DIR"

        # Dangerous option. Permanently deletes expired files and containing
        # directory
        rm -r "$DIR"

        echo "[Current date: $TODAY] Expirified $DIR." >> .expired.log
    fi

done
